### ISSUE TITLE
upgrade packet

### ISSUE THREAD

**Issue by jyao1** [intel/rust-spdm#116]
spin 0.4.10 -> 0.5.2
rustix 0.38.11 -> 0.38.19
time 0.1.45 -> 0.2.23
atty 0.2.14 -> ?

**Comment by longlongyang** [comment]
> spin 0.4.10 -> 0.5.2 rustix 0.38.11 -> 0.38.19 time 0.1.45 -> 0.2.23 atty 0.2.14 -> ?

rustix 0.38.11 -> 0.38.19 ==== Done
time 0.1.45 -> 0.3.28 ==== Done, by upgrade flex_logger to 0.27.2 and simple_logger to 4.2.0
atty 0.2.14 -> ? ==== Done, removed by upgrade flex_logger to 0.27.2

ref: Done in https://github.com/intel/rust-spdm/pull/118

**Comment by longlongyang** [comment]
unfinished: spin 0.4.10 -> 0.5.2 
need @xiaoyuxlu to help this.

**Comment by longlongyang** [comment]
closing this issue, for upgrading spin 0.4.10 -> 0.5.2, please refer to https://github.com/intel/rust-spdm/issues/120.
