### ISSUE TITLE
need upgrade spin 0.4.10 -> 0.5.2

### ISSUE THREAD

**Issue by longlongyang** [intel/rust-spdm#120]
unfinished: spin 0.4.10 -> 0.5.2 
need @xiaoyuxlu to help this.

_Originally posted by @longlongyang in https://github.com/intel/rust-spdm/issues/116#issuecomment-1778241646_

**Comment by xiaoyuxlu** [comment]
Due to the dependency of rust-mbedtls.

rust-mbedtls v0.9.3 it is the latest release in [crates.io](https://crates.io/crates/mbedtls). I submitted an issue to track this ```https://github.com/fortanix/rust-mbedtls/issues/328```. Waiting for fix.

**Comment by xiaoyuxlu** [comment]
PR ```https://github.com/fortanix/rust-mbedtls/pull/329``` has been submitted. Waiting for merge.
