### ISSUE TITLE
Revisit ```auxiliary_app_data``` parameter.

### ISSUE THREAD

**Issue by xiaoyuxlu** [intel/rust-spdm#137]
Need to describe how to use the parameter ```auxiliary_app_data```.

https://github.com/intel/rust-spdm/blob/185ceda2b19bc005d88053d5a016560361e27059/spdmlib/src/responder/app_message_handler.rs#L44

**Comment by jyao1** [comment]
1) We need to change `auxiliary_app_data` to `app_handle`.
2) We need to change `vendor_context` to `vdm_handle`.
3) We need to use same type for them, change to `usize`
4) We need to add comment to describe what it is.

**Comment by jyao1** [comment]
related issue - https://github.com/intel/rust-spdm/issues/37
