### ISSUE TITLE
should get spdmlib stack/heap size only and exclude spem-emu

### ISSUE THREAD

**Issue by jyao1** [intel/rust-spdm#151]
Currently, we collect full spdm-emu stack/heap size, which will be impacted by the async lib e.g. tokio or executor.

**Comment by jyao1** [comment]
Please also provide configuration when collecting data:
1) with asyn or without async
2) if async, use tokio or executor
3) what is opt level
4) debug/release
5) with or without hash-transcript data
6) raw spdmlib or with-emu
7) log output on/off

**Comment by longlongyang** [comment]
default opt-level 3 + release profile + debug log off
