### ISSUE TITLE
need clear watchdog in write_spdm_heartbeat_response()

### ISSUE THREAD

**Issue by jyao1** [intel/rust-spdm#20]
currently, no such callback.

Also need start watchdog in finish/psk_finish and psk_exchange without context.

**Comment by longlongyang** [comment]
> currently, no such callback.
> 
> Also need start watchdog in finish/psk_finish and psk_exchange without context.

In libspdm implementation, the reset watchdog action happens at every session messages reception, not just heartbeat.

https://github.com/DMTF/libspdm/blob/2b625eaf7e4a6d2f1208c5bd1c06263d361b243e/library/spdm_responder_lib/libspdm_rsp_receive_send.c#L809-L811
