### ISSUE TITLE
Responder will skip the mutual authentication if requester does not support it

### ISSUE THREAD

**Issue by jyao1** [intel/rust-spdm#25]
Shall responder send back error if mut-auth feature is selected but requester does not support mutual authentication?

**Comment by xiaoyuxlu** [comment]
#67

**Comment by longlongyang** [comment]
Since #67 is fixed, this can be closed now.
if mandatory mutual authentication is not enabled, responder will skip mutual authentication process if requester doesn't support it.
if mandatory mutual authentication will reject to establish session if requester doesn't support mutual authentication.
