### ISSUE TITLE
/sh_script/build.sh not working.

### ISSUE THREAD

**Issue by xiaoyuxlu** [intel/rust-spdm#48]
commit 4480332e9eefdb08e4fecb3dedb899009e5d6345

**current behavior**
/sh_script/build.sh -h start building.
/sh_script/build.sh -r  tests didn't run.

**expected behavior**
/sh_script/build.sh -h dump help message
/sh_script/build.sh -r  start running test.

**Comment by jyao1** [comment]
We need to figure out why this does not cause CI failure, and think out potential improvement on how to better catch it in CI next time.
