### ISSUE TITLE
Tests fail while CI passed

### ISSUE THREAD

**Issue by longlongyang** [intel/rust-spdm#65]
The CI for #59 was passed.
but below test case fails, to reproduce:
1. fetch PR #59 
2. open cmd, run cargo run -p spdm-responder-emu --no-default-features --features=spdm-ring,hashed-transcript-data
3. open cmd, run cargo run -p spdm-requester-emu --no-default-features --features=spdm-mbedtls,hashed-transcript-data,spdm-mbedtls-hashed-transcript-data,mut-auth

**Comment by xiaoyuxlu** [comment]
The mut-auth feature should be enabled in CI.

**Comment by xiaoyuxlu** [comment]
Do we support this feature combination?  One has mut-auth the other does not?

**Comment by jyao1** [comment]
what do you mean support?
The code should not crash at least.

**Comment by longlongyang** [comment]
fixed by https://github.com/intel/rust-spdm/commit/08813adc2ff99e7fbdd1786a2f5d2a5e357c5e23
