### ISSUE TITLE
Remove gen_array and gen_array_clone.

### ISSUE THREAD

**Issue by xiaoyuxlu** [intel/rust-spdm#76]
We can use [T; N] to generate array.
It seems that there is no need for these two functions.

https://github.com/intel/rust-spdm/blob/754082e7e7d51c9637af19e73250d6d8afef20aa/spdmlib/src/protocol/mod.rs#L18-L36

**Comment by longlongyang** [comment]
to Use [T; N] require T is a Copy;
One rule for Copy is `Copy` not allowed on types with destructors.
On secret Structures, a destructor to zero memory is required, So for secret structures, Copy can not be derived.
Closing this issue.
