### ISSUE TITLE
add cargo lock and dependabot

### ISSUE THREAD

**Issue by jyao1** [intel/rust-spdm#91]

**Comment by gaojiaqi7** [comment]
Hi @jyao1 , I recommend not to use `Cargo.lock` in rust-spdm because it's a library crate. Emulators are under the same workspace as the rust-spdm library so we can't add lock file only for emulators.

**Comment by gaojiaqi7** [comment]
Sorry, it's a misunderstanding. Users dependent on `rust-spdm` will ignore the `Cargo.lock` defined in this workspace. See https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries.

So it is fine to add `Cargo.lock` to determine the version of dependencies of binary crates and it will not effect the use of library crates.
